# referenced from https://github.com/salsify/action-detect-and-tag-new-version/tree/v1.0.0
# and https://github.com/marketplace/actions/detect-and-tag-new-version?version=v2.0.1

name: Version-Control

on: 
  # pull_request:
  push:
    branches:
    - main

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            cat about.php 
            cat CreateDatabase.php
            cat CreateTables.php
            cat footer.php 
            cat friendadd.php 
            cat friendlist.php 
            cat index.php 
            cat login.php 
            cat logout.php 
            cat navigation.php 
            cat PopulateTable.php 
            cat settings.php 
            cat signup.php 
            cat system_functions.php 
            cat style/style.css